server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# 改配置已配置在nacos配置管理的引导文件中
#  application: #eureka服务名称
#    name: userservice
  cloud:
    nacos:
      #server-addr: http://127.0.0.1:8848 #注册中心地址
      discovery:
        cluster-name: GZ #集群名称
        #namespace: 54BFBB13362242E9BDAB33C8EEA79E60_dev
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: #注册中心地址
#      defaultZone: http://127.0.0.1:10086/eureka/
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto